package io.joshatron.tak.engine.exception;

public enum TakEngineErrorCode {
    INVALID_BOARD_SIZE,
    NOT_ENOUGH_STONES,
    NOT_ENOUGH_CAPSTONES,
    ILLEGAL_FIRST_MOVE_TYPE,
    INVALID_LOCATION,
    STACK_NOT_EMPTY,
    MOVE_IN_FIRST_TURN,
    INVALID_PICKUP_AMOUNT,
    DO_NOT_OWN_STACK,
    INVALID_PLACE_AMOUNT,
    BLOCKED_FROM_PLACING,
    GAME_FINISHED
}
